### ISSUE TITLE
Test Browser Support

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/paa.gruppe-adler.de#2]
- [x] Chrome (Desktop)
- [x] Firefox (Desktop)
- [x] Opera (Desktop)
- [x] Edge
- [x] Safari (Desktop)

**Comment by DerZade** [comment]
Things to test:
- Adding files via drag-and-drop
- Adding files via button
- Conversion from paa to png
- Conversion from png to paa
- Downloading a single files
- "Download all Files"-Button

**Comment by DerZade** [comment]
Tested the following browsers: 
- Chrome 84
- Firefox 79
- Opera 70 
- "old" Edge (I think it was Version 44)
- "new" Edge 84

**Comment by DerZade** [comment]
@TheWillard tested Safari 13.1

Everything worked but the buttons look weird.

![](https://i.imgur.com/gZt9ykq.png)
![](https://i.imgur.com/r92YidL.png)

**Comment by TheWillard** [comment]
3a588a4 fixed the weird buttons on Safari 13.1
